# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: source/std-data-sync/image_metadata.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)source/std-data-sync/image_metadata.proto\x12\x10std_daq_protocol\"x\n\x0fGFImageMetadata\x12\x0f\n\x07scan_id\x18\x01 \x01(\r\x12\x11\n\tscan_time\x18\x02 \x01(\r\x12\x11\n\tsync_time\x18\x03 \x01(\r\x12\x17\n\x0f\x66rame_timestamp\x18\x04 \x01(\x04\x12\x15\n\rexposure_time\x18\x05 \x01(\x04\"\"\n\x0fJFImageMetadata\x12\x0f\n\x07\x64\x61q_rec\x18\x01 \x01(\x04\"\"\n\x0f\x45GImageMetadata\x12\x0f\n\x07\x65xptime\x18\x01 \x01(\x04\"\xd1\x02\n\rImageMetadata\x12\x10\n\x08image_id\x18\x01 \x01(\x04\x12\x0e\n\x06height\x18\x02 \x01(\x04\x12\r\n\x05width\x18\x03 \x01(\x04\x12\x33\n\x05\x64type\x18\x04 \x01(\x0e\x32$.std_daq_protocol.ImageMetadataDtype\x12\x35\n\x06status\x18\x05 \x01(\x0e\x32%.std_daq_protocol.ImageMetadataStatus\x12/\n\x02gf\x18\x06 \x01(\x0b\x32!.std_daq_protocol.GFImageMetadataH\x00\x12/\n\x02jf\x18\x07 \x01(\x0b\x32!.std_daq_protocol.JFImageMetadataH\x00\x12/\n\x02\x65g\x18\x08 \x01(\x0b\x32!.std_daq_protocol.EGImageMetadataH\x00\x42\x10\n\x0eimage_metadata*\xa2\x01\n\x12ImageMetadataDtype\x12\x0b\n\x07unknown\x10\x00\x12\t\n\x05uint8\x10\x01\x12\n\n\x06uint16\x10\x02\x12\n\n\x06uint32\x10\x04\x12\n\n\x06uint64\x10\x08\x12\x08\n\x04int8\x10\x0b\x12\t\n\x05int16\x10\x0c\x12\t\n\x05int32\x10\x0e\x12\t\n\x05int64\x10\x12\x12\x0b\n\x07\x66loat16\x10\x16\x12\x0b\n\x07\x66loat32\x10\x18\x12\x0b\n\x07\x66loat64\x10\x1c*L\n\x13ImageMetadataStatus\x12\x0e\n\ngood_image\x10\x00\x12\x13\n\x0fmissing_packets\x10\x01\x12\x10\n\x0cid_missmatch\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'source.std_data_sync.image_metadata_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGEMETADATADTYPE._serialized_start=598
  _IMAGEMETADATADTYPE._serialized_end=760
  _IMAGEMETADATASTATUS._serialized_start=762
  _IMAGEMETADATASTATUS._serialized_end=838
  _GFIMAGEMETADATA._serialized_start=63
  _GFIMAGEMETADATA._serialized_end=183
  _JFIMAGEMETADATA._serialized_start=185
  _JFIMAGEMETADATA._serialized_end=219
  _EGIMAGEMETADATA._serialized_start=221
  _EGIMAGEMETADATA._serialized_end=255
  _IMAGEMETADATA._serialized_start=258
  _IMAGEMETADATA._serialized_end=595
# @@protoc_insertion_point(module_scope)
