# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: writer_driver.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import image_metadata_pb2 as image__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13writer_driver.proto\x12\x10std_daq_protocol\x1a\x14image_metadata.proto\"@\n\x07RunInfo\x12\x0e\n\x06run_id\x18\x01 \x01(\x04\x12\x13\n\x0boutput_file\x18\x02 \x01(\t\x12\x10\n\x08n_images\x18\x03 \x01(\x05\"\xa4\x01\n\rWriterCommand\x12\x33\n\x0c\x63ommand_type\x18\x01 \x01(\x0e\x32\x1d.std_daq_protocol.CommandType\x12+\n\x08run_info\x18\x02 \x01(\x0b\x32\x19.std_daq_protocol.RunInfo\x12\x31\n\x08metadata\x18\x03 \x01(\x0b\x32\x1f.std_daq_protocol.ImageMetadata*C\n\x0b\x43ommandType\x12\x0f\n\x0bWRITE_IMAGE\x10\x00\x12\x11\n\rSTART_WRITING\x10\x01\x12\x10\n\x0cSTOP_WRITING\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'writer_driver_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMANDTYPE._serialized_start=296
  _COMMANDTYPE._serialized_end=363
  _RUNINFO._serialized_start=63
  _RUNINFO._serialized_end=127
  _WRITERCOMMAND._serialized_start=130
  _WRITERCOMMAND._serialized_end=294
# @@protoc_insertion_point(module_scope)
