include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  - local: '.gitlab-ci/build-and-test.yml'
  - local: '.gitlab-ci/cache.yml'

test:unit_tests:
  extends: [ .build_and_test ]
  variables:
    DOCKER_IMAGE: paulscherrerinstitute/std_detector_buffer_base:latest
