include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  - local: '.gitlab-ci/cache.yml'
  - local: '.gitlab-ci/build-and-test.yml'
  - local: '.gitlab-ci/package.yml'

stages:
  - test
  - package
  - upload
  - release

variables:
  PACKAGE_REGISTRY_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/std_detector_buffer/${CI_COMMIT_TAG}
  PACKAGE_RPM: std_detector_buffer-${CI_COMMIT_TAG}-Linux.rpm
  PACKAGE_TARGZ: std_detector_buffer-${CI_COMMIT_TAG}-Linux.tar.gz
  DOCKER_IMAGE: paulscherrerinstitute/std_detector_buffer_base:2.1.3

default:
  before_script:
    - |
      source /opt/rh/devtoolset-10/enable
      source /opt/rh/rh-python38/enable
      source /etc/profile.d/modules.sh
      module load mpi
      [ [ -d .venv ] ] && source venv/bin/activate

test_project:
  stage: test
  extends: [ .build_and_test ]
  tags: [ sf-docker ]

package_project:
  stage: package
  extends: [ .package ]
  tags: [ sf-docker ]
