include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  - local: '.gitlab-ci/cache.yml'
  - local: '.gitlab-ci/prepare-env.yml'
  - local: '.gitlab-ci/build-and-test.yml'
  - local: '.gitlab-ci/package.yml'
  - local: '.gitlab-ci/upload.yml'
  - local: '.gitlab-ci/release.yml'
  - local: '.gitlab-ci/docker_build.yml'

stages:
  - test
  - deploy
  - package
  - upload
  - release

variables:
  PACKAGE_REGISTRY_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/std_detector_buffer/${CI_COMMIT_TAG}
  IMAGE_VERSION: "1.1.0"

test_project:
  stage: test
  extends: [ .prepare_env, .cache, .build_and_test ]
  tags: [ sf-docker ]
  parallel:
    matrix:
      - DOCKER_IMAGE: [ "centos8" ]
  rules:
    - when: always

package_project:
  stage: package
  extends: [ .prepare_env, .cache, .package ]
  tags: [ sf-docker ]
  parallel:
    matrix:
      - DOCKER_IMAGE: [ "centos8" ]

upload_project:
  stage: upload
  extends: [ .upload ]
  tags: [ sf-docker ]
  needs:
    - job: package_project
      parallel:
        matrix:
        - DOCKER_IMAGE: [ "centos8" ]
      artifacts: true

release_project:
  stage: release
  extends: [ .release ]
  tags: [ sf-docker ]
  needs:
    - job: upload_project

docker_deploy:
  stage: test
  extends: [ .docker_build ]

pages:
  stage: deploy
  image: node:15.12-alpine3.13
  tags: [ sf-docker ]
  script:
    - cd website/std-daq-doc
    - yarn install
    - yarn build
    - mv ./build ${CI_PROJECT_DIR}/public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - "website/**/*"
    - when: never
