include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  - local: '.gitlab-ci/build-and-test.yml'
  - local: '.gitlab-ci/cache.yml'

default:
  before_script:
    - source /opt/rh/devtoolset-10/enable
    - source /opt/rh/rh-python38/enable
    - source /etc/profile.d/modules.sh
    - module load mpi
    - [ [ -d .venv ] ] && source venv/bin/activate

test:unit_tests:
  extends: [ .build_and_test ]
  tags: [ standard-docker ]
  variables:
    DOCKER_IMAGE: paulscherrerinstitute/std_detector_buffer_base:latest
