# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: start_stop_writer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='start_stop_writer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17start_stop_writer.proto\"Q\n\x07RunInfo\x12\x15\n\x08\x66ilename\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08n_images\x18\x02 \x01(\x05H\x01\x88\x01\x01\x42\x0b\n\t_filenameB\x0b\n\t_n_images\"\xb1\x01\n\rWriterRequest\x12-\n\x04type\x18\x01 \x01(\x0e\x32\x1a.WriterRequest.RequestTypeH\x00\x88\x01\x01\x12\x1b\n\x04info\x18\x02 \x01(\x0b\x32\x08.RunInfoH\x01\x88\x01\x01\"B\n\x0bRequestType\x12\x0e\n\nGET_STATUS\x10\x00\x12\x11\n\rSTART_WRITING\x10\x01\x12\x10\n\x0cSTOP_WRITING\x10\x02\x42\x07\n\x05_typeB\x07\n\x05_info\"X\n\x0cWriterStatus\x12\x15\n\x08\x66ilename\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1b\n\x04info\x18\x02 \x01(\x0b\x32\x08.RunInfoH\x01\x88\x01\x01\x42\x0b\n\t_filenameB\x07\n\x05_info2G\n\x0fStartStopWriter\x12\x34\n\rConnectDriver\x12\x0e.WriterRequest\x1a\r.WriterStatus\"\x00(\x01\x30\x01\x62\x06proto3'
)



_WRITERREQUEST_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='WriterRequest.RequestType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GET_STATUS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='START_WRITING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP_WRITING', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=204,
  serialized_end=270,
)
_sym_db.RegisterEnumDescriptor(_WRITERREQUEST_REQUESTTYPE)


_RUNINFO = _descriptor.Descriptor(
  name='RunInfo',
  full_name='RunInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='RunInfo.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n_images', full_name='RunInfo.n_images', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_filename', full_name='RunInfo._filename',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_n_images', full_name='RunInfo._n_images',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=27,
  serialized_end=108,
)


_WRITERREQUEST = _descriptor.Descriptor(
  name='WriterRequest',
  full_name='WriterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='WriterRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='info', full_name='WriterRequest.info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WRITERREQUEST_REQUESTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_type', full_name='WriterRequest._type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_info', full_name='WriterRequest._info',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=111,
  serialized_end=288,
)


_WRITERSTATUS = _descriptor.Descriptor(
  name='WriterStatus',
  full_name='WriterStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='WriterStatus.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='info', full_name='WriterStatus.info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_filename', full_name='WriterStatus._filename',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_info', full_name='WriterStatus._info',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=290,
  serialized_end=378,
)

_RUNINFO.oneofs_by_name['_filename'].fields.append(
  _RUNINFO.fields_by_name['filename'])
_RUNINFO.fields_by_name['filename'].containing_oneof = _RUNINFO.oneofs_by_name['_filename']
_RUNINFO.oneofs_by_name['_n_images'].fields.append(
  _RUNINFO.fields_by_name['n_images'])
_RUNINFO.fields_by_name['n_images'].containing_oneof = _RUNINFO.oneofs_by_name['_n_images']
_WRITERREQUEST.fields_by_name['type'].enum_type = _WRITERREQUEST_REQUESTTYPE
_WRITERREQUEST.fields_by_name['info'].message_type = _RUNINFO
_WRITERREQUEST_REQUESTTYPE.containing_type = _WRITERREQUEST
_WRITERREQUEST.oneofs_by_name['_type'].fields.append(
  _WRITERREQUEST.fields_by_name['type'])
_WRITERREQUEST.fields_by_name['type'].containing_oneof = _WRITERREQUEST.oneofs_by_name['_type']
_WRITERREQUEST.oneofs_by_name['_info'].fields.append(
  _WRITERREQUEST.fields_by_name['info'])
_WRITERREQUEST.fields_by_name['info'].containing_oneof = _WRITERREQUEST.oneofs_by_name['_info']
_WRITERSTATUS.fields_by_name['info'].message_type = _RUNINFO
_WRITERSTATUS.oneofs_by_name['_filename'].fields.append(
  _WRITERSTATUS.fields_by_name['filename'])
_WRITERSTATUS.fields_by_name['filename'].containing_oneof = _WRITERSTATUS.oneofs_by_name['_filename']
_WRITERSTATUS.oneofs_by_name['_info'].fields.append(
  _WRITERSTATUS.fields_by_name['info'])
_WRITERSTATUS.fields_by_name['info'].containing_oneof = _WRITERSTATUS.oneofs_by_name['_info']
DESCRIPTOR.message_types_by_name['RunInfo'] = _RUNINFO
DESCRIPTOR.message_types_by_name['WriterRequest'] = _WRITERREQUEST
DESCRIPTOR.message_types_by_name['WriterStatus'] = _WRITERSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RunInfo = _reflection.GeneratedProtocolMessageType('RunInfo', (_message.Message,), {
  'DESCRIPTOR' : _RUNINFO,
  '__module__' : 'start_stop_writer_pb2'
  # @@protoc_insertion_point(class_scope:RunInfo)
  })
_sym_db.RegisterMessage(RunInfo)

WriterRequest = _reflection.GeneratedProtocolMessageType('WriterRequest', (_message.Message,), {
  'DESCRIPTOR' : _WRITERREQUEST,
  '__module__' : 'start_stop_writer_pb2'
  # @@protoc_insertion_point(class_scope:WriterRequest)
  })
_sym_db.RegisterMessage(WriterRequest)

WriterStatus = _reflection.GeneratedProtocolMessageType('WriterStatus', (_message.Message,), {
  'DESCRIPTOR' : _WRITERSTATUS,
  '__module__' : 'start_stop_writer_pb2'
  # @@protoc_insertion_point(class_scope:WriterStatus)
  })
_sym_db.RegisterMessage(WriterStatus)



_STARTSTOPWRITER = _descriptor.ServiceDescriptor(
  name='StartStopWriter',
  full_name='StartStopWriter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=380,
  serialized_end=451,
  methods=[
  _descriptor.MethodDescriptor(
    name='ConnectDriver',
    full_name='StartStopWriter.ConnectDriver',
    index=0,
    containing_service=None,
    input_type=_WRITERREQUEST,
    output_type=_WRITERSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STARTSTOPWRITER)

DESCRIPTOR.services_by_name['StartStopWriter'] = _STARTSTOPWRITER

# @@protoc_insertion_point(module_scope)
