.build_and_test:
  image: $CI_REGISTRY/controls-ci/std_detector_buffer/$DOCKER_IMAGE:$USED_DOCKER_IMAGE_VERSION
  entrypoint: ["/bin/bash", "-c"]
  script: |
    echo ">>>>> Release build:"
    cmake -B release -DCMAKE_BUILD_TYPE=Release -G Ninja
    cmake --build release
    echo ">>>>> Unit testing:"
    ctest --test-dir release -VV
    echo ">>>>> Integration testing:"
    [[ ! -d .venv ]] && python3 -m venv .venv
    source .venv/bin/activate
    python3 -m pip install -r requirements.txt
    pytest testing --junitxml=release/integration_tests.xml
#    echo ">>>>> Building Python package:"
#    python3 setup.py bdist_wheel
#    twine upload --skip-existing dist/*
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit: release/*_tests.xml
