.build_and_test:
  image: $DOCKER_IMAGE
  script: |
    echo ">>>>> Release build:"
    cmake -B release -DCMAKE_BUILD_TYPE=Release -G Ninja
    cmake --build release
    echo ">>>>> Deploy shortcut - copy to /ioc/modules/patro_m in sf:"
    cp -r release /ioc/modules/patro_m
    echo ">>>>> Unit testing:"
    ctest --test-dir release -VV
    echo ">>>>> Integration testing:"
    [[ ! -d .venv ]] && python3 -m venv .venv
    source .venv/bin/activate
    python3 -m pip install -r requirements.txt
    pytest testing --junitxml=release/integration_tests.xml
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit: release/*_tests.xml
