variables:
  CONAN_USER_HOME: $CI_PROJECT_DIR/.conan_cache

.cache:
  cache:
    key:
      files:
        - conan/conanfile.py
        - requirements.txt
      prefix: $DOCKER_IMAGE
    paths:
      - $CONAN_USER_HOME
      - .venv
