include:
  - project: 'controls-ci/templates'
    file: '/docker/build_image_template.yml'

.docker_build:
  extends: .build_image_template
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/controls-ci/std_detector_buffer/$DOCKER_IMAGE:$BUILT_DOCKER_IMAGE_VERSION -f docker/$DOCKER_IMAGE.Dockerfile .
    - docker push $CI_REGISTRY/controls-ci/std_detector_buffer/$DOCKER_IMAGE:$BUILT_DOCKER_IMAGE_VERSION
  parallel:
    matrix:
      - DOCKER_IMAGE: [ centos8 ]
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - docker/**
