.package:
  image: $DOCKER_IMAGE
  only: [ tags ]
  variables:
    PACKAGE_VERSION: $CI_COMMIT_TAG
  script:
    |
      echo ">>>>> Release build:"
      cmake -B release -DCMAKE_BUILD_TYPE=Release -G Ninja
      cmake --build release --target all
      python3 -m pip install -r testing/requirements.txt
      cmake --build release --target pyinstall
      echo ">>>>> Create Package"
      cmake --build release --target package
  artifacts:
    when: on_success
    expire_in: 1 day
    paths:
      - release/std_detector_buffer*.rpm
      - release/std_detector_buffer*.tar.gz
