.package:
  image: $CI_REGISTRY/controls-ci/std_detector_buffer/$DOCKER_IMAGE:$IMAGE_VERSION
  entrypoint: [ "/bin/bash", "-c" ]
  only: [ tags ]
  variables:
    PACKAGE_VERSION: $CI_COMMIT_TAG
  script:
    |
      echo ">>>>> Release build:"
      cmake -B release -DCMAKE_BUILD_TYPE=Release -G Ninja
      cmake --build release --target all
      python3 -m pip install -r requirements.txt
      cmake --build release --target pyinstall
      echo ">>>>> Create Package"
      cmake --build release --target package
      mv release/std_detector_buffer-${CI_COMMIT_TAG}-Linux.rpm release/sdb-${CI_COMMIT_TAG}-${DOCKER_IMAGE}.rpm
  artifacts:
    when: on_success
    expire_in: 1 day
    paths:
      - release/sdb*.rpm
