.release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  only: [ tags ]
  script:
    - |
      release-cli create \
        --name "Release $CI_COMMIT_TAG" \
        --tag-name $CI_COMMIT_TAG \
        --description CHANGELOG.md \
        --assets-link "{\"name\":\"${PACKAGE_RPM}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PACKAGE_RPM}\"}" \
        --assets-link "{\"name\":\"${PACKAGE_TARGZ}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PACKAGE_TARGZ}\"}"
