.release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  only: [ tags ]
  script:
    - |
      release-cli create \
        --name "Release $CI_COMMIT_TAG" \
        --tag-name $CI_COMMIT_TAG \
        --description CHANGELOG.md \
        --assets-link "{\"name\":\"sdb-${CI_COMMIT_TAG}-centos8.rpm\",\"url\":\"${PACKAGE_REGISTRY_URL}/sdb-${CI_COMMIT_TAG}-centos8.rpm\"}"
