version: '3.8'

services:
  rest_primary:
    build:
      context: .
      dockerfile: restprimary.Dockerfile
    environment:
      CONFIG_FILE: /etc/std_daq/configs/gf1.json
      REST_PORT: 5000
      SECONDARY_SERVER: http://xbl-daq-28:5001
    volumes:
      - /etc/std_daq/configs/gf1.json:/etc/std_daq/configs/gf1.json:rw
      - /gpfs/:/gpfs/
    logging:
      driver: journald
    network_mode: host
    privileged: true
