name: 'workflow_cache'
description: 'caching for conan and python packages'

runs:
  using: "composite"
  steps:
    - name: cache
      uses: actions/cache@v2
      with:
        path: |
          ${{ env.CONAN_USER_HOME }}
          venv
        key: ${{ hashFiles('./conan/conanfile.py')}}-${{ hashFiles('./requirements.txt')}}
