{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: std_buffer
  version: {{ data.get('version') }}

source:
  path: ..

requirements:
  build:
    - python
  run:
    - python
    - pyzmq
    - numpy
    - h5py


build:
  noarch: python
  number: 4
  preserve_egg_dir: True
  script: python setup.py install

about:
  home: https://github.com/paulscherrerinstitute/std_detector_buffer

